<?php
/* Class created by Francisco Presencia Fandos under GNU GPL 3+. Feel free to use and share. *
 * Minimize CSS or Javascript
 * 
 */
class Minimize
  {
  private $Production = 0;
  
  public function __construct($Folder, $Type)
    {
    $this->type  = $Type;
    $this->retrieve($Folder);
    
    $this->code  =  "/* " . $Type . " autogenerated. \n ";
    $this->code .= " * @Author  Francisco Presencia Fandos \n ";
    $this->code .= " * @Page    http://libreuniversity.org \n ";
    $this->code .= " * @Date    " . date('Y-m-d H:i:s') . " \n ";
    $this->code .= " */ \n";
    
    if ($Production)
      $this->code .= $this->remove($this->uncompressed);
    else
      $this->code .= $this->uncompressed;
    }
  
  private function retrieve ($Folder)
    {
    $this->uncompressed = '';
    $File = ($Type == 'css') ? 'style.css' : 'javascript.js';
    
    // Add some extra information for debugging (where the css comes from). Useful for development.
    foreach (glob($Folder . "/*." . $this->type) as $Gen)
      $this->uncompressed .= " \n\n /* From the core file: " . strrchr( $Gen , '/' ) . " */ \n " . file_get_contents($Gen);
    }
    
  private function remove ( $fulltext )
    {
    // Remove comments
    $fulltext = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $fulltext);

    // Remove space after colons
    $fulltext = str_replace(': ', ':', $fulltext);

    // Remove whitespace
    return str_replace(array("\r\n", "\r", "\n", "\t", '  ', '    ', '    '), '', $fulltext);
    }
  
  public function write ($Path)
    {
    $ourFileHandle = fopen($Path, 'w');
    fwrite($ourFileHandle, $this->code);
    fclose($ourFileHandle);
    }
  }
